// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvwkj0iTLakIp_daO85UCLBRiq9CzoKRU',
    appId: '1:539261450051:web:6d69ce1994ae1a676b61f6',
    messagingSenderId: '539261450051',
    projectId: 'ts-31986',
    authDomain: 'ts-31986.firebaseapp.com',
    storageBucket: 'ts-31986.appspot.com',
    measurementId: 'G-XQN7TCSFJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4fYG7CzXzZdHU3g4g-TuDpgi69YYYAG4',
    appId: '1:539261450051:android:914e93bc06f87e3f6b61f6',
    messagingSenderId: '539261450051',
    projectId: 'ts-31986',
    storageBucket: 'ts-31986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7e6H_wFhikcIZmSJtPU-3znqqLOaAFQ',
    appId: '1:539261450051:ios:2ec50f0a639685796b61f6',
    messagingSenderId: '539261450051',
    projectId: 'ts-31986',
    storageBucket: 'ts-31986.appspot.com',
    iosClientId: '539261450051-7ssu8dals3hk1p0hskcjbp624cvu26pb.apps.googleusercontent.com',
    iosBundleId: 'com.china.ts70',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7e6H_wFhikcIZmSJtPU-3znqqLOaAFQ',
    appId: '1:539261450051:ios:2ec50f0a639685796b61f6',
    messagingSenderId: '539261450051',
    projectId: 'ts-31986',
    storageBucket: 'ts-31986.appspot.com',
    iosClientId: '539261450051-7ssu8dals3hk1p0hskcjbp624cvu26pb.apps.googleusercontent.com',
    iosBundleId: 'com.china.ts70',
  );
}
